-- map-signal: tell the save watcher which screen the player is on.
-- Generated by tools/build-map-signal-mod.py -- edit that, not this file.
--
-- The save file cannot answer "is the star map open": FTL writes it during encounters
-- and is silent while the player plans a route. Hyperspace exposes the flag the game
-- itself uses, and log() writes somewhere an outside process can read -- FTL_HS.log.
-- One line per transition, nothing drawn, nothing changed.

local PREFIX = "map-signal: "

local last_open = nil     -- nil until the first read, so the first state is announced
local reported = {}       -- failure sites already logged, so a fault cannot spam

local function report(key, msg)
    if reported[key] then return end
    reported[key] = true
    log(PREFIX .. msg)
end

local function star_map()
    local ok, map = pcall(function()
        return Hyperspace.Global.GetInstance():GetCApp().world.starMap
    end)
    if not ok or map == nil then
        report("starmap", "starMap unavailable: " .. tostring(map))
        return nil
    end
    return map
end

local function sector_of(map)
    -- worldLevel is 0-based, as everywhere else in the API. Only ever a sanity check
    -- for a human reading the log: the watcher takes the sector from the engine's own
    -- generation lines, which name the type rather than the number.
    --
    -- Two things the first live run showed. Lua prints a number as "2.0", so it is
    -- formatted as an integer. And at the main menu, before a run is loaded, the field
    -- holds uninitialised memory -- one launch logged "sector 1835609917" -- so a value
    -- outside the eight real sectors is reported as unknown rather than as fact.
    local ok, level = pcall(function() return map.worldLevel end)
    if not ok or level == nil then return "?" end
    local n = math.floor(level) + 1
    if n < 1 or n > 8 then return "?" end
    return string.format("%d", n)
end

local function tick()
    local map = star_map()
    if map == nil then return end
    local ok, open = pcall(function() return map.bOpen and true or false end)
    if not ok then
        report("bopen", "bOpen unreadable: " .. tostring(open))
        return
    end
    if open == last_open then return end
    last_open = open
    log(PREFIX .. (open and "open" or "closed") .. " sector " .. sector_of(map))
end

-- MOUSE_CONTROL is the one render hook that fires on every screen including the map
-- (BEACON-REVEAL.md 3.2). Nothing is drawn here -- it is a per-frame callback, and the
-- body is two field reads and an early return.
script.on_render_event(Defines.RenderEvents.MOUSE_CONTROL, tick, function() end)

log(PREFIX .. "loaded")
