-- map-signal: tell the save watcher which screen the player is on.
-- Generated by tools/build-map-signal-mod.py -- edit that, not this file.
--
-- The save file cannot answer "is the star map open": FTL writes it during encounters
-- and is silent while the player plans a route. Hyperspace exposes the flag the game
-- itself uses, and log() writes somewhere an outside process can read -- FTL_HS.log.
-- One line per transition, nothing drawn, nothing changed.

local PREFIX = "map-signal: "

local last_open = nil      -- nil until the first read, so the first state is announced
local last_choosing = nil  -- ...same for the sector-choice screen
local reported = {}       -- failure sites already logged, so a fault cannot spam

local function report(key, msg)
    if reported[key] then return end
    reported[key] = true
    log(PREFIX .. msg)
end

local function star_map()
    local ok, map = pcall(function()
        return Hyperspace.Global.GetInstance():GetCApp().world.starMap
    end)
    if not ok or map == nil then
        report("starmap", "starMap unavailable: " .. tostring(map))
        return nil
    end
    return map
end

local function sector_of(map)
    -- worldLevel is 0-based, as everywhere else in the API. Only ever a sanity check
    -- for a human reading the log: the watcher takes the sector from the engine's own
    -- generation lines, which name the type rather than the number.
    --
    -- Two things the first live run showed. Lua prints a number as "2.0", so it is
    -- formatted as an integer. And at the main menu, before a run is loaded, the field
    -- holds uninitialised memory -- one launch logged "sector 1835609917" -- so a value
    -- outside the eight real sectors is reported as unknown rather than as fact.
    local ok, level = pcall(function() return map.worldLevel end)
    if not ok or level == nil then return "?" end
    local n = math.floor(level) + 1
    if n < 1 or n > 8 then return "?" end
    return string.format("%d", n)
end

-- What the SWIG bindings actually expose on an object, logged once per label.
--
-- Which StarMap and Sector members Hyperspace exposes is not stated by anything in
-- this repo -- `raw/modding/2026-08-15-beacon-name-labels-mod.md` lists the ones it
-- verified and leaves the sector-choice screen an open question. Rather than guess in
-- a loop, the script asks: SWIG keeps attributes in the metatable's `.get`/`.set`
-- tables and methods in `.fn`, so reading those names *is* the API surface. This fires
-- only when an attempt below fails, and only once, so a working install logs nothing.
-- `rawget` is NOT available: Hyperspace's sandbox strips it along with io, os, package
-- and debug. Measured 2026-08-16 -- the first version of this probe called it and threw
-- "attempt to call a nil value (global 'rawget')" out of the render hook, which aborted
-- the tick before it could log anything useful. Plain indexing, guarded, only.
local CANDIDATE_FIELDS = {
    "neighbors", "neighbours", "reachable", "visited", "level", "type",
    "description", "location", "sectors", "currentSector", "worldLevel",
    "bChoosingNewSector", "bOpen", "locations", "currentLoc", "potentialLoc",
}

local dumped = {}
local function probe(label, obj)
    if dumped[label] then return end
    dumped[label] = true

    -- 1. The binding's own member tables. SWIG keeps attributes in `.get`/`.set` and
    --    methods in `.fn`, so these names *are* the API surface -- no guessing.
    local ok, mt = pcall(getmetatable, obj)
    if ok and type(mt) == "table" then
        local top = {}
        for k in pairs(mt) do top[#top + 1] = tostring(k) end
        table.sort(top)
        log(PREFIX .. "probe " .. label .. " meta: " .. table.concat(top, ","))
        for _, key in ipairs({".get", ".set", ".fn"}) do
            local got, tbl = pcall(function() return mt[key] end)
            if got and type(tbl) == "table" then
                local names = {}
                for k in pairs(tbl) do names[#names + 1] = tostring(k) end
                table.sort(names)
                log(PREFIX .. "probe " .. label .. " " .. key .. ": "
                    .. table.concat(names, ","))
            end
        end
    else
        log(PREFIX .. "probe " .. label .. ": no metatable")
    end

    -- 2. ...and what actually reads, in case the tables above are empty or hidden.
    --    Reported as name:type, since a vector and a number need different handling.
    local found = {}
    for _, field in ipairs(CANDIDATE_FIELDS) do
        local got, value = pcall(function() return obj[field] end)
        if got and value ~= nil then
            found[#found + 1] = field .. ":" .. type(value)
        end
    end
    log(PREFIX .. "probe " .. label .. " reads: " .. table.concat(found, ","))
end

-- A diagnostic must never be the thing that breaks the hook it is diagnosing.
local function safe_probe(label, obj)
    pcall(probe, label, obj)
end

local function name_of(sector)
    local ok, name = pcall(function() return sector.description.name:GetText() end)
    if ok and name ~= nil and name ~= "" then return name end
    return nil
end

-- Everything the choice screen can be asked about, logged once, because the offer is
-- not where it was expected. Measured 2026-08-16: Hyperspace exposes exactly three
-- members on a Sector -- description, level, visited -- so the engine's own adjacency
-- (`neighbors`, `reachable`) is not reachable from Lua at all. What is left to check:
--
--   1. whether `locations` / `connectedLocations` are repurposed to hold the *sectors*
--      while the sector map is up. That is the open question in
--      raw/modding/2026-08-15-beacon-name-labels-mod.md, and nobody has answered it.
--   2. the shape of the sector tree by level, which at worst gives the next column --
--      a superset of the offer, honestly labelled, rather than a guess at the offer.
--   3. whether Hyperspace publishes an event for the choice itself.
local choice_probed = false
local function probe_choice(map)
    if choice_probed then return end
    choice_probed = true

    local function say(msg) log(PREFIX .. "probe " .. msg) end

    local ok, size = pcall(function() return map.locations:size() end)
    say("locations while choosing: " .. (ok and tostring(size) or "unreadable"))
    ok = pcall(function()
        local cur = map.currentLoc
        local conn = cur.connectedLocations
        local names = {}
        for i = 0, conn:size() - 1 do
            local got, name = pcall(function() return conn[i].event.eventName end)
            names[#names + 1] = (got and name ~= "" and name) or "?"
        end
        say("currentLoc connects to " .. conn:size() .. ": " .. table.concat(names, ","))
    end)
    if not ok then say("currentLoc.connectedLocations unreadable") end

    -- The tree, grouped by column. Bounded output: one line per level.
    ok = pcall(function()
        local sectors = map.sectors
        local by_level = {}
        for i = 0, sectors:size() - 1 do
            local s = sectors[i]
            local level = math.floor(s.level)
            local name = name_of(s) or "?"
            if s.visited then name = name .. "*" end
            by_level[level] = (by_level[level] and (by_level[level] .. ",") or "") .. name
        end
        for level = 0, 7 do
            if by_level[level] then
                say("tree L" .. level .. ": " .. by_level[level])
            end
        end
    end)
    if not ok then say("sectors unreadable") end

    pcall(function() probe("description", map.currentSector.description) end)

    -- Hyperspace's own event tables are plain Lua tables, so their keys are readable.
    for _, group in ipairs({"InternalEvents", "RenderEvents", "TextEvents"}) do
        pcall(function()
            local tbl = Defines[group]
            if type(tbl) ~= "table" then return end
            local names = {}
            for k in pairs(tbl) do names[#names + 1] = tostring(k) end
            table.sort(names)
            say("Defines." .. group .. ": " .. table.concat(names, ","))
        end)
    end
end

-- The next column of the sector map -- which is NOT quite the offer, and the line this
-- logs says so.
--
-- Measured 2026-08-16, by probing the live bindings rather than guessing:
--
--   * Hyperspace exposes three members on a Sector: description, level, visited. The
--     engine's own adjacency (`neighbors`, `reachable`) is not bound to Lua at all.
--   * `locations` is not repurposed while the sector map is up -- it still holds the
--     current sector's 24 beacons, and currentLoc.connectedLocations returns beacon
--     events. That answers the open question in the beacon-name-labels research.
--   * `Defines.InternalEvents` publishes no sector-choice hook.
--
-- What is left is `sectors` filtered by level, which is the column the player is
-- choosing from: a superset of the two or three they can actually reach. xftl documents
-- the linking rules ("4 prev, 2 now: 1st links to previous 1st/2nd...") but loosely, and
-- re-deriving them would risk naming the wrong sectors -- worse than naming a few extra.
-- So the column is reported as a column, and the page says so.
local function offer(map)
    local ok, current = pcall(function() return map.currentSector end)
    if not ok or current == nil then
        report("currentSector", "currentSector unreadable")
        safe_probe("starMap", map)
        return nil
    end
    local got, level = pcall(function() return math.floor(current.level) end)
    if not got or level == nil then
        report("level", "currentSector.level unreadable")
        safe_probe("sector", current)
        return nil
    end
    local sectors
    got, sectors = pcall(function() return map.sectors end)
    if not got or sectors == nil then
        report("sectors", "starMap.sectors unreadable")
        safe_probe("starMap", map)
        return nil
    end
    local names = {}
    got = pcall(function()
        for i = 0, sectors:size() - 1 do
            local s = sectors[i]
            if math.floor(s.level) == level + 1 then
                local name = name_of(s)
                if name then names[#names + 1] = name end
            end
        end
    end)
    if not got then
        report("walk", "walking sectors failed")
        return nil
    end
    return names
end

local function tick()
    local map = star_map()
    if map == nil then return end

    local ok, open = pcall(function() return map.bOpen and true or false end)
    if not ok then
        report("bopen", "bOpen unreadable: " .. tostring(open))
        return
    end
    if open ~= last_open then
        last_open = open
        log(PREFIX .. (open and "open" or "closed") .. " sector " .. sector_of(map))
    end

    -- The sector map -- the screen that offers the next sectors -- is a different
    -- screen from the beacon map, and the watcher wants the offer, not just the fact.
    local got, choosing = pcall(function() return map.bChoosingNewSector and true or false end)
    if not got then
        report("choosing", "bChoosingNewSector unreadable: " .. tostring(choosing))
        safe_probe("starMap", map)
        return
    end
    if choosing == last_choosing then return end
    last_choosing = choosing
    if not choosing then
        log(PREFIX .. "chosen")
        return
    end
    local names = offer(map)
    if not names or #names == 0 then
        pcall(probe_choice, map)   -- only when there is nothing to report
    end
    -- "column" is load-bearing: it tells the watcher these are the sectors in the next
    -- column, not a verified list of the ones this sector connects to.
    log(PREFIX .. "choosing " .. sector_of(map) .. " column -> "
        .. ((names and #names > 0) and table.concat(names, " | ") or "?"))
end

-- MOUSE_CONTROL is the one render hook that fires on every screen including the map
-- (BEACON-REVEAL.md 3.2). Nothing is drawn here -- it is a per-frame callback, and the
-- body is two field reads and an early return.
script.on_render_event(Defines.RenderEvents.MOUSE_CONTROL, tick, function() end)

log(PREFIX .. "loaded")
