#!/usr/bin/env python3
"""Build the `map-signal` FTL mod: tell the save watcher when the star map is open.

    python tools/build-map-signal-mod.py            # generate mods/map-signal/src/
    python tools/build-map-signal-mod.py --pack     # ... and zip it to map-signal.ftl
    python tools/build-map-signal-mod.py --install  # ... and patch it into the game
    python tools/build-map-signal-mod.py --verify   # re-check a generated tree

One question the save file cannot answer: *is the star map open*. FTL writes the run
save during encounters and is silent while the player sits on the map planning a
route, so `tools/save-watch.py` had to approximate it (`SAVE-WATCH.md` §5b). Hyperspace
exposes the flag the game itself uses -- `starMap.bOpen` -- and `log()` puts a line
somewhere a process outside the game can read it: `FTL_HS.log`. The watcher tails that.

That is the entire mod. It draws nothing, changes no event, choice, reward or ship, and
writes no save byte; it emits one log line per open/closed transition. The normative
description is `SAVE-WATCH.md` §5c, because the mod exists only to serve the watcher.

Requires FTL Hyperspace, and a restart: the game reads Lua from ftl.dat at startup.
"""

import argparse
import importlib.util
import pathlib
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
MOD = ROOT / "mods" / "map-signal"
SRC = MOD / "src"
SLIPSTREAM = pathlib.Path(r"C:\Users\jparr\Documents\Slipstream")
GAME = pathlib.Path(r"D:\Steam\steamapps\common\FTL Faster Than Light")

LUA_NAME = "map-signal.lua"

# What a full patch applies, in order. Hyperspace first -- this mod adds a <script> to
# the <scripts> element Hyperspace defines, so that element must exist already.
#
# This list is the *current* install plus this mod, read off Slipstream's own log
# rather than assumed: `--patch` reverts to vanilla first and then applies exactly what
# it is given, so a wrong list silently uninstalls whatever it omits. `beacon-reveal`
# is deliberately absent -- it is opt-in, and was not installed when this was written
# (BEACON-REVEAL.md §1a). Its builder carries `map-signal.ftl` in its own PATCH_ORDER,
# so installing that mod keeps this one rather than dropping it.
PATCH_ORDER = ["Hyperspace.ftl", "event-labels.ftl", "map-signal.ftl"]

# The line shape the watcher parses. Kept here as the mod's half of the contract; the
# verify step checks it against the watcher's actual regex, so the two cannot drift.
PREFIX = "map-signal: "

METADATA = """<?xml version="1.0" encoding="UTF-8"?>
<metadata>
\t<title><![CDATA[ Map Signal ]]></title>
\t<threadUrl><![CDATA[ https://subsetgames.com/ftl_mods.html ]]></threadUrl>
\t<author><![CDATA[ generated from an FTL event wiki ]]></author>
\t<version><![CDATA[ 1.0 ]]></version>
\t<description>
<![CDATA[
Logs one line to FTL_HS.log whenever the star map is opened or closed, so a program
outside the game can tell which screen the player is on. Nothing is drawn and nothing
about the game changes.

Written for the save watcher in this repo, which shows an event card on a second
monitor and wants to show the sector profile while the map is up.

Requires FTL Hyperspace.
]]>
\t</description>
</metadata>
"""

# Advanced XML: add one <script> child to Hyperspace's existing <scripts> element.
# A plain append would declare a second <scripts>, which hyperspace.xml forbids
# (BEACON-REVEAL.md §4).
APPEND = """<mod:findLike type="scripts">
\t<mod-append:script>data/%s</mod-append:script>
</mod:findLike>
""" % LUA_NAME

LUA = '''-- map-signal: tell the save watcher which screen the player is on.
-- Generated by tools/build-map-signal-mod.py -- edit that, not this file.
--
-- The save file cannot answer "is the star map open": FTL writes it during encounters
-- and is silent while the player plans a route. Hyperspace exposes the flag the game
-- itself uses, and log() writes somewhere an outside process can read -- FTL_HS.log.
-- One line per transition, nothing drawn, nothing changed.

local PREFIX = "%%PREFIX%%"

local last_open = nil      -- nil until the first read, so the first state is announced
local last_choosing = nil  -- ...same for the sector-choice screen
local reported = {}       -- failure sites already logged, so a fault cannot spam

local function report(key, msg)
    if reported[key] then return end
    reported[key] = true
    log(PREFIX .. msg)
end

local function star_map()
    local ok, map = pcall(function()
        return Hyperspace.Global.GetInstance():GetCApp().world.starMap
    end)
    if not ok or map == nil then
        report("starmap", "starMap unavailable: " .. tostring(map))
        return nil
    end
    return map
end

local function sector_of(map)
    -- worldLevel is 0-based, as everywhere else in the API. Only ever a sanity check
    -- for a human reading the log: the watcher takes the sector from the engine's own
    -- generation lines, which name the type rather than the number.
    --
    -- Two things the first live run showed. Lua prints a number as "2.0", so it is
    -- formatted as an integer. And at the main menu, before a run is loaded, the field
    -- holds uninitialised memory -- one launch logged "sector 1835609917" -- so a value
    -- outside the eight real sectors is reported as unknown rather than as fact.
    local ok, level = pcall(function() return map.worldLevel end)
    if not ok or level == nil then return "?" end
    local n = math.floor(level) + 1
    if n < 1 or n > 8 then return "?" end
    return string.format("%d", n)
end

-- What the SWIG bindings actually expose on an object, logged once per label.
--
-- Which StarMap and Sector members Hyperspace exposes is not stated by anything in
-- this repo -- `raw/modding/2026-08-15-beacon-name-labels-mod.md` lists the ones it
-- verified and leaves the sector-choice screen an open question. Rather than guess in
-- a loop, the script asks: SWIG keeps attributes in the metatable's `.get`/`.set`
-- tables and methods in `.fn`, so reading those names *is* the API surface. This fires
-- only when an attempt below fails, and only once, so a working install logs nothing.
-- `rawget` is NOT available: Hyperspace's sandbox strips it along with io, os, package
-- and debug. Measured 2026-08-16 -- the first version of this probe called it and threw
-- "attempt to call a nil value (global 'rawget')" out of the render hook, which aborted
-- the tick before it could log anything useful. Plain indexing, guarded, only.
local CANDIDATE_FIELDS = {
    "neighbors", "neighbours", "reachable", "visited", "level", "type",
    "description", "location", "sectors", "currentSector", "worldLevel",
    "bChoosingNewSector", "bOpen", "locations", "currentLoc", "potentialLoc",
}

local dumped = {}
local function probe(label, obj)
    if dumped[label] then return end
    dumped[label] = true

    -- 1. The binding's own member tables. SWIG keeps attributes in `.get`/`.set` and
    --    methods in `.fn`, so these names *are* the API surface -- no guessing.
    local ok, mt = pcall(getmetatable, obj)
    if ok and type(mt) == "table" then
        local top = {}
        for k in pairs(mt) do top[#top + 1] = tostring(k) end
        table.sort(top)
        log(PREFIX .. "probe " .. label .. " meta: " .. table.concat(top, ","))
        for _, key in ipairs({".get", ".set", ".fn"}) do
            local got, tbl = pcall(function() return mt[key] end)
            if got and type(tbl) == "table" then
                local names = {}
                for k in pairs(tbl) do names[#names + 1] = tostring(k) end
                table.sort(names)
                log(PREFIX .. "probe " .. label .. " " .. key .. ": "
                    .. table.concat(names, ","))
            end
        end
    else
        log(PREFIX .. "probe " .. label .. ": no metatable")
    end

    -- 2. ...and what actually reads, in case the tables above are empty or hidden.
    --    Reported as name:type, since a vector and a number need different handling.
    local found = {}
    for _, field in ipairs(CANDIDATE_FIELDS) do
        local got, value = pcall(function() return obj[field] end)
        if got and value ~= nil then
            found[#found + 1] = field .. ":" .. type(value)
        end
    end
    log(PREFIX .. "probe " .. label .. " reads: " .. table.concat(found, ","))
end

-- A diagnostic must never be the thing that breaks the hook it is diagnosing.
local function safe_probe(label, obj)
    pcall(probe, label, obj)
end

local function name_of(sector)
    local ok, name = pcall(function() return sector.description.name:GetText() end)
    if ok and name ~= nil and name ~= "" then return name end
    return nil
end

-- Everything the choice screen can be asked about, logged once, because the offer is
-- not where it was expected. Measured 2026-08-16: Hyperspace exposes exactly three
-- members on a Sector -- description, level, visited -- so the engine's own adjacency
-- (`neighbors`, `reachable`) is not reachable from Lua at all. What is left to check:
--
--   1. whether `locations` / `connectedLocations` are repurposed to hold the *sectors*
--      while the sector map is up. That is the open question in
--      raw/modding/2026-08-15-beacon-name-labels-mod.md, and nobody has answered it.
--   2. the shape of the sector tree by level, which at worst gives the next column --
--      a superset of the offer, honestly labelled, rather than a guess at the offer.
--   3. whether Hyperspace publishes an event for the choice itself.
local choice_probed = false
local function probe_choice(map)
    if choice_probed then return end
    choice_probed = true

    local function say(msg) log(PREFIX .. "probe " .. msg) end

    local ok, size = pcall(function() return map.locations:size() end)
    say("locations while choosing: " .. (ok and tostring(size) or "unreadable"))
    ok = pcall(function()
        local cur = map.currentLoc
        local conn = cur.connectedLocations
        local names = {}
        for i = 0, conn:size() - 1 do
            local got, name = pcall(function() return conn[i].event.eventName end)
            names[#names + 1] = (got and name ~= "" and name) or "?"
        end
        say("currentLoc connects to " .. conn:size() .. ": " .. table.concat(names, ","))
    end)
    if not ok then say("currentLoc.connectedLocations unreadable") end

    -- The tree, grouped by column. Bounded output: one line per level.
    ok = pcall(function()
        local sectors = map.sectors
        local by_level = {}
        for i = 0, sectors:size() - 1 do
            local s = sectors[i]
            local level = math.floor(s.level)
            local name = name_of(s) or "?"
            if s.visited then name = name .. "*" end
            by_level[level] = (by_level[level] and (by_level[level] .. ",") or "") .. name
        end
        for level = 0, 7 do
            if by_level[level] then
                say("tree L" .. level .. ": " .. by_level[level])
            end
        end
    end)
    if not ok then say("sectors unreadable") end

    pcall(function() probe("description", map.currentSector.description) end)

    -- Hyperspace's own event tables are plain Lua tables, so their keys are readable.
    for _, group in ipairs({"InternalEvents", "RenderEvents", "TextEvents"}) do
        pcall(function()
            local tbl = Defines[group]
            if type(tbl) ~= "table" then return end
            local names = {}
            for k in pairs(tbl) do names[#names + 1] = tostring(k) end
            table.sort(names)
            say("Defines." .. group .. ": " .. table.concat(names, ","))
        end)
    end
end

-- The next column of the sector map -- which is NOT quite the offer, and the line this
-- logs says so.
--
-- Measured 2026-08-16, by probing the live bindings rather than guessing:
--
--   * Hyperspace exposes three members on a Sector: description, level, visited. The
--     engine's own adjacency (`neighbors`, `reachable`) is not bound to Lua at all.
--   * `locations` is not repurposed while the sector map is up -- it still holds the
--     current sector's 24 beacons, and currentLoc.connectedLocations returns beacon
--     events. That answers the open question in the beacon-name-labels research.
--   * `Defines.InternalEvents` publishes no sector-choice hook.
--
-- What is left is `sectors` filtered by level, which is the column the player is
-- choosing from: a superset of the two or three they can actually reach. xftl documents
-- the linking rules ("4 prev, 2 now: 1st links to previous 1st/2nd...") but loosely, and
-- re-deriving them would risk naming the wrong sectors -- worse than naming a few extra.
-- So the column is reported as a column, and the page says so.
-- Which of the next column the player can actually travel to, or nil for "cannot say".
--
-- The engine's adjacency is not bound to Lua, so this reproduces the generation itself.
-- Recovered from StarMap::AddSectorColumn in the shipped binary, 2026-08-17 --
-- raw/modding/2026-08-17-sector-column-linking-disassembly.md has the disassembly and
-- the reconstruction. All six transitions a run can take are covered.
--
-- A column holds 2..4 sectors, re-rolled only while equal to the previous column, so
-- |n - m| is 1 except for the two cases the code special-cases outright:
--
--   m=2, n=4  new 1st/2nd hang off prev 1st; new 3rd/4th off prev 2nd
--   m=4, n=2  new jth hangs off prev 2j and 2j+1
--   n = m+1   the general loop, with one extra sector created at peer 1
--   n = m-1   the general loop, breaking before the last peer creates anything
--
-- m=1 (leaving the first sector) is forced: the whole column hangs off it.
local function reachable(m, n, mine, column)
    if mine == nil then return nil end
    if m == 1 then return column end

    local pick = {}
    local function take(i)
        if column[i] then pick[#pick + 1] = column[i] end
    end

    if m == 2 and n == 4 then
        take(2 * mine - 1)
        take(2 * mine)
    elseif m == 4 and n == 2 then
        take(math.floor((mine - 1) / 2) + 1)
    elseif n == m + 1 then
        -- Peer p is linked to the sector created for p-1 and to its own.
        take(mine)
        take(mine + 1)
    elseif n == m - 1 then
        -- ...and the last peer only inherits, because the loop breaks before it
        -- creates anything of its own.
        if mine > 1 then take(mine - 1) end
        if mine < m then take(mine) end
    else
        return nil   -- a column shape the generation cannot produce
    end

    if #pick == 0 then return nil end
    return pick
end

local function offer(map)
    local ok, current = pcall(function() return map.currentSector end)
    if not ok or current == nil then
        report("currentSector", "currentSector unreadable")
        safe_probe("starMap", map)
        return nil
    end
    local got, level = pcall(function() return math.floor(current.level) end)
    if not got or level == nil then
        report("level", "currentSector.level unreadable")
        safe_probe("sector", current)
        return nil
    end
    local sectors
    got, sectors = pcall(function() return map.sectors end)
    if not got or sectors == nil then
        report("sectors", "starMap.sectors unreadable")
        safe_probe("starMap", map)
        return nil
    end
    -- Both columns in the engine's own vector order, which is the order the linking
    -- rules count in ("1st", "2nd", ...). Verified 2026-08-16 against a live choice:
    -- a 2-wide column into a 4-wide one offered the first two names to the player
    -- sitting in the 1st sector, which is what the 2-prev/4-now rule says.
    local here, next_col = {}, {}
    got = pcall(function()
        for i = 0, sectors:size() - 1 do
            local s = sectors[i]
            local at = math.floor(s.level)
            if at == level then
                here[#here + 1] = {name = name_of(s), visited = s.visited and true or false}
            elseif at == level + 1 then
                next_col[#next_col + 1] = name_of(s) or false
            end
        end
    end)
    if not got then
        report("walk", "walking sectors failed")
        return nil
    end
    if #next_col == 0 then return nil end

    -- Where the player sits in their own column. Only one sector per column is ever
    -- visited -- you pass through exactly one -- so the flag identifies it without
    -- needing pointer equality on the userdata, which SWIG does not promise.
    local mine, seen = nil, 0
    for i, s in ipairs(here) do
        if s.visited then
            seen = seen + 1
            mine = i
        end
    end
    if seen ~= 1 then mine = nil end   -- not one visited sector: no index, no rule

    -- A name that would not read leaves a false in the column. The rules count
    -- positions, so a hole means the positions cannot be trusted and the exact
    -- answer is off the table -- but the column can still be reported.
    local named, whole = true, {}
    for i = 1, #next_col do
        if next_col[i] then whole[#whole + 1] = next_col[i] else named = false end
    end

    local reach = named and reachable(#here, #next_col, mine, next_col) or nil
    if reach then return reach, true end
    return whole, false
end

local function tick()
    local map = star_map()
    if map == nil then return end

    local ok, open = pcall(function() return map.bOpen and true or false end)
    if not ok then
        report("bopen", "bOpen unreadable: " .. tostring(open))
        return
    end
    if open ~= last_open then
        last_open = open
        log(PREFIX .. (open and "open" or "closed") .. " sector " .. sector_of(map))
    end

    -- The sector map -- the screen that offers the next sectors -- is a different
    -- screen from the beacon map, and the watcher wants the offer, not just the fact.
    local got, choosing = pcall(function() return map.bChoosingNewSector and true or false end)
    if not got then
        report("choosing", "bChoosingNewSector unreadable: " .. tostring(choosing))
        safe_probe("starMap", map)
        return
    end
    if choosing == last_choosing then return end
    last_choosing = choosing
    if not choosing then
        log(PREFIX .. "chosen")
        return
    end
    local names, exact = offer(map)
    if not names or #names == 0 then
        pcall(probe_choice, map)   -- only when there is nothing to report
    end
    -- "column" is load-bearing: it says these are the sectors in the next column, not
    -- the ones this sector connects to. It is dropped only when the transition is one
    -- the generation rules pin down, in which case the list is the offer itself.
    log(PREFIX .. "choosing " .. sector_of(map) .. (exact and "" or " column") .. " -> "
        .. ((names and #names > 0) and table.concat(names, " | ") or "?"))
end

-- MOUSE_CONTROL is the one render hook that fires on every screen including the map
-- (BEACON-REVEAL.md 3.2). Nothing is drawn here -- it is a per-frame callback, and the
-- body is two field reads and an early return.
script.on_render_event(Defines.RenderEvents.MOUSE_CONTROL, tick, function() end)

log(PREFIX .. "loaded")
'''.replace("%%PREFIX%%", PREFIX)   # token substitution, not %-formatting: the Lua
                                    # contains string.format("%d", ...) of its own


def build():
    (SRC / "data").mkdir(parents=True, exist_ok=True)
    (SRC / "mod-appendix").mkdir(parents=True, exist_ok=True)
    (SRC / "data" / LUA_NAME).write_text(LUA, encoding="utf-8", newline="\n")
    (SRC / "data" / "hyperspace.xml.append").write_text(APPEND, encoding="utf-8", newline="\n")
    (SRC / "mod-appendix" / "metadata.xml").write_text(METADATA, encoding="utf-8", newline="\n")


def watcher_pattern():
    """The watcher's own compiled regex, loaded from its source.

    Imported rather than restated: this mod and `save-watch.py` are two halves of one
    contract, and the failure mode if they drift is silent -- the mod logs happily and
    the watcher ignores every line.
    """
    spec = importlib.util.spec_from_file_location(
        "_sw", str(ROOT / "tools" / "save-watch.py"))
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(ROOT / "tools"))
    spec.loader.exec_module(module)
    return module


def verify():
    problems = []
    lua = (SRC / "data" / LUA_NAME).read_text(encoding="utf-8")
    append = (SRC / "data" / "hyperspace.xml.append").read_text(encoding="utf-8")
    meta = (SRC / "mod-appendix" / "metadata.xml").read_text(encoding="utf-8")

    # FTL's font has no glyph above 0x7E; a stray dash would render as a box.
    for i, ch in enumerate(lua):
        if ord(ch) > 0x7E:
            problems.append("non-ASCII %r at offset %d in the Lua" % (ch, i))
            break

    # Hyperspace warns that double registration is easy and costly -- the hook would
    # run twice per frame.
    hooks = len(re.findall(r"script\.on_render_event", lua))
    if hooks != 1:
        problems.append("expected exactly 1 script.on_render_event, found %d" % hooks)

    # The mod is a signal, not a mod: any drawing call means it grew a second job.
    for banned in ("Graphics.freetype", "CSurface.GL_", "Hyperspace.ships",
                   "SaveGame", "bMapRevealed"):
        if banned in lua:
            problems.append("draws or mutates (%s) -- this mod must only log" % banned)

    # Hyperspace's sandbox has no io/os/package/debug -- and no rawget/rawset either,
    # measured the hard way: a probe that called rawget threw out of the render hook.
    # Comments are stripped first, or the note explaining that trips the check.
    code = "\n".join(line.split("--", 1)[0] for line in lua.splitlines())
    for absent in ("rawget", "rawset", "io.", "os.", "require", "debug."):
        if absent in code:
            problems.append("uses %r, which Hyperspace's Lua sandbox does not provide"
                            % absent)

    # Every failure path has to be survivable: a raw field read inside the per-frame
    # hook could take the game down with it.
    if lua.count("pcall") < 3:
        problems.append("fewer than 3 pcall guards; the render hook must not throw")

    # The contract with the watcher, checked against the watcher's real regexes.
    watcher = watcher_pattern()
    pattern = getattr(watcher, "MAP_SIGNAL", None)
    choice = getattr(watcher, "SECTOR_CHOICE", None)
    if pattern is None or choice is None:
        problems.append("save-watch.py exposes no MAP_SIGNAL / SECTOR_CHOICE to check against")
    else:
        # Both forms: what the mod emits, and what the log actually receives --
        # Hyperspace stamps `[Lua]: ` on every scripted line, and testing only the
        # bare form is exactly how a regex anchored at ^ passed here and matched
        # nothing in the real file.
        for line in (PREFIX + "open sector 3", PREFIX + "closed sector 3",
                     "[Lua]: " + PREFIX + "open sector 3",
                     "[Lua]: " + PREFIX + "closed sector 3   "):
            match = pattern.search(line)
            if not match:
                problems.append("watcher regex does not match %r" % line)
            elif match.group(1) not in ("open", "closed"):
                problems.append("watcher regex captures %r from %r"
                                % (match.group(1), line))
        # ... and must ignore the lines that are not state, or "loaded" would read
        # as a transition.
        for line in (PREFIX + "loaded", PREFIX + "starMap unavailable: nil",
                     "[Lua]: " + PREFIX + "loaded"):
            if pattern.search(line):
                problems.append("watcher regex wrongly matches %r" % line)

        # ...and the same for the sector-choice pair, which is a separate pattern and
        # must not be confused with the open/closed one in either direction.
        offer = "[Lua]: " + PREFIX + "choosing 4 -> Rock Homeworlds | Slug Home Nebula   "
        done = "[Lua]: " + PREFIX + "chosen"
        for line, verb in ((offer, "choosing"), (done, "chosen")):
            match = choice.search(line)
            if not match or match.group(1) != verb:
                problems.append("SECTOR_CHOICE does not read %r as %r" % (line, verb))
            if pattern.search(line):
                problems.append("MAP_SIGNAL wrongly matches the choice line %r" % line)
        if choice.search(PREFIX + "open sector 3"):
            problems.append("SECTOR_CHOICE wrongly matches an open/closed line")
        names = choice.search(offer).group(2).split("->", 1)[1]
        if [n.strip() for n in names.split(watcher.CHOICE_SPLIT)] !=                 ["Rock Homeworlds", "Slug Home Nebula"]:
            problems.append("the watcher's CHOICE_SPLIT does not recover the offer")

    # Slipstream adds the <FTL> root itself; a wrapper here nests it twice.
    if "<FTL>" in append:
        problems.append("the append carries an <FTL> wrapper")
    if "<scripts>" in append:
        problems.append("the append declares its own <scripts> (only one is allowed)")
    if "mod:findLike" not in append or "mod-append:script" not in append:
        problems.append("the append does not edit Hyperspace's <scripts> in place")
    try:
        ET.fromstring("<root xmlns:mod='m' xmlns:mod-append='a'>%s</root>" % append)
    except ET.ParseError as exc:
        problems.append("the append is not well-formed XML: %s" % exc)

    # Slipstream's metadata reader is strict: five elements, none empty, or it rejects
    # the whole mod.
    try:
        root = ET.fromstring(meta)
        for tag in ("title", "threadUrl", "author", "version", "description"):
            node = root.find(tag)
            if node is None or not (node.text or "").strip():
                problems.append("metadata.xml: <%s> missing or empty" % tag)
    except ET.ParseError as exc:
        problems.append("metadata.xml is not well-formed: %s" % exc)

    return problems


def pack():
    MOD.mkdir(parents=True, exist_ok=True)
    out = MOD / "map-signal.ftl"
    files = sorted(p for p in SRC.rglob("*") if p.is_file())
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for path in files:
            # Fixed timestamps keep the archive byte-identical between builds.
            info = zipfile.ZipInfo(str(path.relative_to(SRC)).replace("\\", "/"),
                                   date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, path.read_bytes())
    return out


def install():
    """Copy the .ftl to Slipstream and patch it into the game.

    Requires FTL closed -- Slipstream cannot rewrite ftl.dat underneath a running game,
    and the game reads its Lua at startup, so a patch applied to a running instance
    does nothing visible and looks like a broken mod.
    """
    import shutil
    import subprocess

    ftl = MOD / "map-signal.ftl"
    if not ftl.exists():
        raise SystemExit("no map-signal.ftl -- run with --pack first")
    shutil.copy2(ftl, SLIPSTREAM / "mods" / ftl.name)

    result = subprocess.run(
        ["java", "-jar", "modman.jar", "--patch"] + PATCH_ORDER,
        cwd=SLIPSTREAM, capture_output=True, text=True)
    tail = (result.stdout + result.stderr).strip().splitlines()[-3:]
    for line in tail:
        print("         %s" % line.strip())
    if result.returncode != 0:
        raise SystemExit("slipstream patch failed (exit %d)" % result.returncode)
    dat = GAME / "ftl.dat"
    print("patched  %s at %s"
          % (dat, __import__("datetime").datetime.fromtimestamp(
              dat.stat().st_mtime).strftime("%H:%M:%S")))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pack", action="store_true", help="zip src/ into map-signal.ftl")
    ap.add_argument("--install", action="store_true",
                    help="pack, copy to Slipstream, and patch the game (FTL must be closed)")
    ap.add_argument("--verify", action="store_true",
                    help="re-check an already-generated tree without rebuilding")
    args = ap.parse_args()

    if not args.verify:
        build()
        print("built    %s" % SRC)

    problems = verify()
    if problems:
        for problem in problems:
            print("FAIL     %s" % problem)
        return 1
    print("verified the Lua, the metadata, the hyperspace.xml patch, and the "
          "watcher's parse of every line this mod can log")

    if args.pack or args.install:
        out = pack()
        print("packed   %s (%d bytes)" % (out, out.stat().st_size))
    if args.install:
        install()
        print("restart FTL through mods\\fullscreen-no-minimize\\launch-ftl.cmd")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
