#!/usr/bin/env python3
"""Build the `map-signal` FTL mod: tell the save watcher when the star map is open.

    python tools/build-map-signal-mod.py            # generate mods/map-signal/src/
    python tools/build-map-signal-mod.py --pack     # ... and zip it to map-signal.ftl
    python tools/build-map-signal-mod.py --install  # ... and patch it into the game
    python tools/build-map-signal-mod.py --verify   # re-check a generated tree

One question the save file cannot answer: *is the star map open*. FTL writes the run
save during encounters and is silent while the player sits on the map planning a
route, so `tools/save-watch.py` had to approximate it (`SAVE-WATCH.md` §5b). Hyperspace
exposes the flag the game itself uses -- `starMap.bOpen` -- and `log()` puts a line
somewhere a process outside the game can read it: `FTL_HS.log`. The watcher tails that.

That is the entire mod. It draws nothing, changes no event, choice, reward or ship, and
writes no save byte; it emits one log line per open/closed transition. The normative
description is `SAVE-WATCH.md` §5c, because the mod exists only to serve the watcher.

Requires FTL Hyperspace, and a restart: the game reads Lua from ftl.dat at startup.
"""

import argparse
import importlib.util
import pathlib
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
MOD = ROOT / "mods" / "map-signal"
SRC = MOD / "src"
SLIPSTREAM = pathlib.Path(r"C:\Users\jparr\Documents\Slipstream")
GAME = pathlib.Path(r"D:\Steam\steamapps\common\FTL Faster Than Light")

LUA_NAME = "map-signal.lua"

# What a full patch applies, in order. Hyperspace first -- this mod adds a <script> to
# the <scripts> element Hyperspace defines, so that element must exist already.
#
# This list is the *current* install plus this mod, read off Slipstream's own log
# rather than assumed: `--patch` reverts to vanilla first and then applies exactly what
# it is given, so a wrong list silently uninstalls whatever it omits. `beacon-reveal`
# is deliberately absent -- it is opt-in, and was not installed when this was written
# (BEACON-REVEAL.md §1a). Its builder carries `map-signal.ftl` in its own PATCH_ORDER,
# so installing that mod keeps this one rather than dropping it.
PATCH_ORDER = ["Hyperspace.ftl", "event-labels.ftl", "map-signal.ftl"]

# The line shape the watcher parses. Kept here as the mod's half of the contract; the
# verify step checks it against the watcher's actual regex, so the two cannot drift.
PREFIX = "map-signal: "

METADATA = """<?xml version="1.0" encoding="UTF-8"?>
<metadata>
\t<title><![CDATA[ Map Signal ]]></title>
\t<threadUrl><![CDATA[ https://subsetgames.com/ftl_mods.html ]]></threadUrl>
\t<author><![CDATA[ generated from an FTL event wiki ]]></author>
\t<version><![CDATA[ 1.0 ]]></version>
\t<description>
<![CDATA[
Logs one line to FTL_HS.log whenever the star map is opened or closed, so a program
outside the game can tell which screen the player is on. Nothing is drawn and nothing
about the game changes.

Written for the save watcher in this repo, which shows an event card on a second
monitor and wants to show the sector profile while the map is up.

Requires FTL Hyperspace.
]]>
\t</description>
</metadata>
"""

# Advanced XML: add one <script> child to Hyperspace's existing <scripts> element.
# A plain append would declare a second <scripts>, which hyperspace.xml forbids
# (BEACON-REVEAL.md §4).
APPEND = """<mod:findLike type="scripts">
\t<mod-append:script>data/%s</mod-append:script>
</mod:findLike>
""" % LUA_NAME

LUA = '''-- map-signal: tell the save watcher which screen the player is on.
-- Generated by tools/build-map-signal-mod.py -- edit that, not this file.
--
-- The save file cannot answer "is the star map open": FTL writes it during encounters
-- and is silent while the player plans a route. Hyperspace exposes the flag the game
-- itself uses, and log() writes somewhere an outside process can read -- FTL_HS.log.
-- One line per transition, nothing drawn, nothing changed.

local PREFIX = "%%PREFIX%%"

local last_open = nil     -- nil until the first read, so the first state is announced
local reported = {}       -- failure sites already logged, so a fault cannot spam

local function report(key, msg)
    if reported[key] then return end
    reported[key] = true
    log(PREFIX .. msg)
end

local function star_map()
    local ok, map = pcall(function()
        return Hyperspace.Global.GetInstance():GetCApp().world.starMap
    end)
    if not ok or map == nil then
        report("starmap", "starMap unavailable: " .. tostring(map))
        return nil
    end
    return map
end

local function sector_of(map)
    -- worldLevel is 0-based, as everywhere else in the API. Only ever a sanity check
    -- for a human reading the log: the watcher takes the sector from the engine's own
    -- generation lines, which name the type rather than the number.
    --
    -- Two things the first live run showed. Lua prints a number as "2.0", so it is
    -- formatted as an integer. And at the main menu, before a run is loaded, the field
    -- holds uninitialised memory -- one launch logged "sector 1835609917" -- so a value
    -- outside the eight real sectors is reported as unknown rather than as fact.
    local ok, level = pcall(function() return map.worldLevel end)
    if not ok or level == nil then return "?" end
    local n = math.floor(level) + 1
    if n < 1 or n > 8 then return "?" end
    return string.format("%d", n)
end

local function tick()
    local map = star_map()
    if map == nil then return end
    local ok, open = pcall(function() return map.bOpen and true or false end)
    if not ok then
        report("bopen", "bOpen unreadable: " .. tostring(open))
        return
    end
    if open == last_open then return end
    last_open = open
    log(PREFIX .. (open and "open" or "closed") .. " sector " .. sector_of(map))
end

-- MOUSE_CONTROL is the one render hook that fires on every screen including the map
-- (BEACON-REVEAL.md 3.2). Nothing is drawn here -- it is a per-frame callback, and the
-- body is two field reads and an early return.
script.on_render_event(Defines.RenderEvents.MOUSE_CONTROL, tick, function() end)

log(PREFIX .. "loaded")
'''.replace("%%PREFIX%%", PREFIX)   # token substitution, not %-formatting: the Lua
                                    # contains string.format("%d", ...) of its own


def build():
    (SRC / "data").mkdir(parents=True, exist_ok=True)
    (SRC / "mod-appendix").mkdir(parents=True, exist_ok=True)
    (SRC / "data" / LUA_NAME).write_text(LUA, encoding="utf-8", newline="\n")
    (SRC / "data" / "hyperspace.xml.append").write_text(APPEND, encoding="utf-8", newline="\n")
    (SRC / "mod-appendix" / "metadata.xml").write_text(METADATA, encoding="utf-8", newline="\n")


def watcher_pattern():
    """The watcher's own compiled regex, loaded from its source.

    Imported rather than restated: this mod and `save-watch.py` are two halves of one
    contract, and the failure mode if they drift is silent -- the mod logs happily and
    the watcher ignores every line.
    """
    spec = importlib.util.spec_from_file_location(
        "_sw", str(ROOT / "tools" / "save-watch.py"))
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(ROOT / "tools"))
    spec.loader.exec_module(module)
    return getattr(module, "MAP_SIGNAL", None)


def verify():
    problems = []
    lua = (SRC / "data" / LUA_NAME).read_text(encoding="utf-8")
    append = (SRC / "data" / "hyperspace.xml.append").read_text(encoding="utf-8")
    meta = (SRC / "mod-appendix" / "metadata.xml").read_text(encoding="utf-8")

    # FTL's font has no glyph above 0x7E; a stray dash would render as a box.
    for i, ch in enumerate(lua):
        if ord(ch) > 0x7E:
            problems.append("non-ASCII %r at offset %d in the Lua" % (ch, i))
            break

    # Hyperspace warns that double registration is easy and costly -- the hook would
    # run twice per frame.
    hooks = len(re.findall(r"script\.on_render_event", lua))
    if hooks != 1:
        problems.append("expected exactly 1 script.on_render_event, found %d" % hooks)

    # The mod is a signal, not a mod: any drawing call means it grew a second job.
    for banned in ("Graphics.freetype", "CSurface.GL_", "Hyperspace.ships",
                   "SaveGame", "bMapRevealed"):
        if banned in lua:
            problems.append("draws or mutates (%s) -- this mod must only log" % banned)

    # Every failure path has to be survivable: a raw field read inside the per-frame
    # hook could take the game down with it.
    if lua.count("pcall") < 3:
        problems.append("fewer than 3 pcall guards; the render hook must not throw")

    # The contract with the watcher, checked against the watcher's real regex.
    pattern = watcher_pattern()
    if pattern is None:
        problems.append("save-watch.py exposes no MAP_SIGNAL pattern to check against")
    else:
        # Both forms: what the mod emits, and what the log actually receives --
        # Hyperspace stamps `[Lua]: ` on every scripted line, and testing only the
        # bare form is exactly how a regex anchored at ^ passed here and matched
        # nothing in the real file.
        for line in (PREFIX + "open sector 3", PREFIX + "closed sector 3",
                     "[Lua]: " + PREFIX + "open sector 3",
                     "[Lua]: " + PREFIX + "closed sector 3   "):
            match = pattern.search(line)
            if not match:
                problems.append("watcher regex does not match %r" % line)
            elif match.group(1) not in ("open", "closed"):
                problems.append("watcher regex captures %r from %r"
                                % (match.group(1), line))
        # ... and must ignore the lines that are not state, or "loaded" would read
        # as a transition.
        for line in (PREFIX + "loaded", PREFIX + "starMap unavailable: nil",
                     "[Lua]: " + PREFIX + "loaded"):
            if pattern.search(line):
                problems.append("watcher regex wrongly matches %r" % line)

    # Slipstream adds the <FTL> root itself; a wrapper here nests it twice.
    if "<FTL>" in append:
        problems.append("the append carries an <FTL> wrapper")
    if "<scripts>" in append:
        problems.append("the append declares its own <scripts> (only one is allowed)")
    if "mod:findLike" not in append or "mod-append:script" not in append:
        problems.append("the append does not edit Hyperspace's <scripts> in place")
    try:
        ET.fromstring("<root xmlns:mod='m' xmlns:mod-append='a'>%s</root>" % append)
    except ET.ParseError as exc:
        problems.append("the append is not well-formed XML: %s" % exc)

    # Slipstream's metadata reader is strict: five elements, none empty, or it rejects
    # the whole mod.
    try:
        root = ET.fromstring(meta)
        for tag in ("title", "threadUrl", "author", "version", "description"):
            node = root.find(tag)
            if node is None or not (node.text or "").strip():
                problems.append("metadata.xml: <%s> missing or empty" % tag)
    except ET.ParseError as exc:
        problems.append("metadata.xml is not well-formed: %s" % exc)

    return problems


def pack():
    MOD.mkdir(parents=True, exist_ok=True)
    out = MOD / "map-signal.ftl"
    files = sorted(p for p in SRC.rglob("*") if p.is_file())
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for path in files:
            # Fixed timestamps keep the archive byte-identical between builds.
            info = zipfile.ZipInfo(str(path.relative_to(SRC)).replace("\\", "/"),
                                   date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, path.read_bytes())
    return out


def install():
    """Copy the .ftl to Slipstream and patch it into the game.

    Requires FTL closed -- Slipstream cannot rewrite ftl.dat underneath a running game,
    and the game reads its Lua at startup, so a patch applied to a running instance
    does nothing visible and looks like a broken mod.
    """
    import shutil
    import subprocess

    ftl = MOD / "map-signal.ftl"
    if not ftl.exists():
        raise SystemExit("no map-signal.ftl -- run with --pack first")
    shutil.copy2(ftl, SLIPSTREAM / "mods" / ftl.name)

    result = subprocess.run(
        ["java", "-jar", "modman.jar", "--patch"] + PATCH_ORDER,
        cwd=SLIPSTREAM, capture_output=True, text=True)
    tail = (result.stdout + result.stderr).strip().splitlines()[-3:]
    for line in tail:
        print("         %s" % line.strip())
    if result.returncode != 0:
        raise SystemExit("slipstream patch failed (exit %d)" % result.returncode)
    dat = GAME / "ftl.dat"
    print("patched  %s at %s"
          % (dat, __import__("datetime").datetime.fromtimestamp(
              dat.stat().st_mtime).strftime("%H:%M:%S")))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pack", action="store_true", help="zip src/ into map-signal.ftl")
    ap.add_argument("--install", action="store_true",
                    help="pack, copy to Slipstream, and patch the game (FTL must be closed)")
    ap.add_argument("--verify", action="store_true",
                    help="re-check an already-generated tree without rebuilding")
    args = ap.parse_args()

    if not args.verify:
        build()
        print("built    %s" % SRC)

    problems = verify()
    if problems:
        for problem in problems:
            print("FAIL     %s" % problem)
        return 1
    print("verified the Lua, the metadata, the hyperspace.xml patch, and the "
          "watcher's parse of every line this mod can log")

    if args.pack or args.install:
        out = pack()
        print("packed   %s (%d bytes)" % (out, out.stat().st_size))
    if args.install:
        install()
        print("restart FTL through mods\\fullscreen-no-minimize\\launch-ftl.cmd")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
